### PR TITLE
Better visual flow.

### PR DESCRIPTION
**Pull request by RlonRyan**

### CODE REVIEW

**Comment by AbrarSyed** [comment]
-_- rly?

**Comment by RlonRyan** [comment]
#### Yes.

**Comment by RlonRyan** [comment]
# You must appease the OCD gods you know!

**Comment by yuuka-miya** [comment]
DENIED. [chop]

**Comment by RlonRyan** [comment]
@luacs1998 The ground trembles beneath your feet. A horrible realization dawns upon you.

# You have angered the OCD gods!

**Comment by RlonRyan** [comment]
Lol just kidding.

**Pull request closed without merging**
